### ISSUE TITLE
Pretrained model not available 

### ISSUE THREAD

**Issue by WikkAI** [ostadabbas/Infant-Pose-Estimation#1]
Dear Huang, Fu & Ostadabbas,

In the Quick Start section of the Readme, a GoogleDrive link is provided for the pretrained FiDIP model. However, when the link is followed GoogleDrive informs me that the file has been deleted and is no longer available. The links to the other models are working. Could the link the to the pretrained FiDIP model be restored?

Kind regards,
Wikke

**Comment by FayeHuang0621** [comment]
Hi WikkAI,

We modified our model and dataset last week but didn't update our repo in time. We will upload the new version today. Sorry for the inconvenience. 

Best,
Xiaofei

**Comment by WikkAI** [comment]
Thank you!
