### ISSUE TITLE
FiDIP pretrained models

### ISSUE THREAD

**Issue by diegosancarmen** [ostadabbas/Infant-Pose-Estimation#15]
Hello,

In  your paper "[Invariant Representation Learning for Infant Pose Estimation with Small Data](https://arxiv.org/pdf/2010.06100)" specifically in Table IV, you provide figures for generalization of the FiDIP method on three baseline models: SimpleBaseline, DarkPose, and MobileNet. However, in the models [Google Drive](https://drive.google.com/drive/folders/108P-1SnTqaj3xNtjYZ1o7T8z6UvUYuiC) folder, there are only two FiDIP models, HRNet (DarkPose) and MobileNet. Would you also be able to release the SimpleBaseline + FiDIP model?

Thank you!

**Comment by FayeHuang0621** [comment]
Since the SimpleBaseline + FiDIP model is built on another pose estimation repository, I hadn't planned to release it. It's been three years, and I'm unsure if I can dig it out. However, I'll send it to you if I find it.

**Comment by diegosancarmen** [comment]
Hello @FayeHuang0621,

Thank you for your quick reply. Actually, would you be able to share the config and training files used for generating this model instead of the actual weights? 

Thank you!

**Comment by FayeHuang0621** [comment]
Please look at the [old version of this repo](https://github.com/ostadabbas/Infant-Pose-Estimation/tree/7b7e2b688d4af2568abb0760fa45d918daea88ba)
