### ISSUE TITLE
Question about downloading pre-trained model and data

### ISSUE THREAD

**Issue by ljr10225008** [ostadabbas/Infant-Pose-Estimation#3]
Next to meet you! I am a researcher now analyzing infants' body motions and found your super nice software. But I met some trouble when downloading the pre-trained model and data preparation.
1) the pytorch model zoo link does not direct to a download link of model.
2) The google drive link for FiDIP pretrained model requires for a approvement that I can not get into.
3) I did not find a /model/pytorch folder under my downloading folder after completing the installation. Should I create the folders manually and organize the downloaded models in the folder by hand?
4) Could you tell me how to download the prepared data from SyRIP dataset? I find .json files in the folders but do not know how to download the files using .json from the link.

I am sorry that I am not professional in programming and it will be my pleasure if you can spend few time to help me solve the problems.

Thanks in advance
Li

**Comment by huhubrave** [comment]
@ljr10225008 
Do you have access to  FiDIP pretrained model?

You can use "wget" to download the SyRIP dataset
