### ISSUE TITLE
Wrong Link in Paper

### ISSUE THREAD

**Issue by marco-rudolph** [ostadabbas/Infant-Pose-Estimation#7]
Hey,

thanks for this repo! I just want to inform you that the github link in your paper has a little typo ("-" is missing).

Best,
Marco

**Comment by ostadabbas** [comment]
Thanks Marco! Are you referring to our paper in arXiv: https://arxiv.org/pdf/2010.06100.pdf

The link seems to be working for me.

**Comment by marco-rudolph** [comment]
I copied the link from your IEEE-Version (which has the same faulty link text as in arxiv) - but you are right, the link behind the text (in arxiv) is the right one. I just wanted to let you know...

**Comment by zky-1217** [comment]
我在IEEE上找到链接，那个链接确实不太对 。姐！
